# Generated by Django 5.1.6 on 2025-02-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
