# Generated by Django 5.1.6 on 2025-02-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_delete_imagetag_delete_tag'),
        ('tagger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='images', to='tagger.tag'),
        ),
    ]
